apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- simple-fe-rollout.yaml
- simple-fe-svc.yaml
- simple-fe-svc-preview.yaml


images:
- name: yongman50/simple-fe
  newTag: "v3.1.0"